build-and-deploy

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -43,77 +43,82 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Build Docker image
-        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME}} .
+        run: |
+          docker build \
+          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
+          --build-arg DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
+          --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
+          -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }} .
 
       - name: Push Docker image to Docker Hub
         run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME}}
 
-      - name: Configure AWS CLI
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
-
-      - name: Check for existing EC2 instance
-        id: check_instance
-        run: |
-          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=new-key" --query 'Reservations[0].Instances[0].InstanceId' --output text)
-          if [ "$INSTANCE_ID" = "None" ]; then
-            echo "::set-output name=instance_exists::false"
-          else
-            INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].State.Name' --output text)
-            if [ "$INSTANCE_STATE" = "terminated" ]; then
-              echo "::set-output name=instance_exists::false"
-            else
-              echo "::set-output name=instance_exists::true"
-              echo "::set-output name=instance_id::$INSTANCE_ID"
-            fi
-          fi
-
-      - name: Create EC2 instance (if not exists or terminated)
-        if: steps.check_instance.outputs.instance_exists == 'false'
-        id: create_ec2
-        run: |
-          VPC_ID=$(aws ec2 describe-vpcs --query 'Vpcs[0].VpcId' --output text)
-          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=cloud-sss" --query "SecurityGroups[0].GroupId" --output text)
-
-          if [ "$SECURITY_GROUP_ID" = "None" ]; then
-            SECURITY_GROUP_ID=$(aws ec2 create-security-group --group-name cloud-sss --description "Security group for cloud instance" --vpc-id $VPC_ID --output text)
-            aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 22 --cidr 0.0.0.0/0
-            aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 9090 --cidr 0.0.0.0/0
-          else
-            echo "Reusing existing security group: $SECURITY_GROUP_ID"
-          fi
-
-          INSTANCE_ID=$(aws ec2 run-instances --image-id ami-0866a3c8686eaeeba --count 1 --instance-type t2.micro --key-name new-key --security-group-ids $SECURITY_GROUP_ID --user-data file://install-docker.sh --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=new-key},{Key=Environment,Value=development}]' --query 'Instances[0].InstanceId' --output text)
-
-          echo "::set-output name=instance_id::$INSTANCE_ID"
-
-      - name: Wait for EC2 instance to be running
-        if: steps.create_ec2.outputs.instance_id != '' || steps.check_instance.outputs.instance_exists == 'true'
-        run: |
-          INSTANCE_ID=${{ steps.create_ec2.outputs.instance_id || steps.check_instance.outputs.instance_id }}
-          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
-          echo "EC2 instance $INSTANCE_ID is now running."
-
-      - name: Create new-key.pem file
-        run: |
-          echo "${{ secrets.EC2_KEY }}" > new-key.pem
-          chmod 600 new-key.pem
-
-      - name: Create Docker network on EC2
-        run: |
-          INSTANCE_ID=${{ steps.create_ec2.outputs.instance_id || steps.check_instance.outputs.instance_id }}
-          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
-          ssh -o StrictHostKeyChecking=no -i new-key.pem ubuntu@$PUBLIC_IP "sudo docker network create my-network || true"
-
-      - name: Ensure PostgreSQL container exists
-        run: |
-          INSTANCE_ID=${{ steps.create_ec2.outputs.instance_id || steps.check_instance.outputs.instance_id }}
-          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
-          if ssh -o StrictHostKeyChecking=no -i new-key.pem ubuntu@$PUBLIC_IP "docker ps -a -q -f name=postgres-container"; then
-            echo "PostgreSQL container already exists."
-          else
-            echo "PostgreSQL container not found. Creating a new one..."
-            ssh -o StrictHostKeyChecking=no -i new-key.pem ubuntu@$PUBLIC_IP "sudo docker run -d --name postgres-container --network my-network
+#      - name: Configure AWS CLI
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          aws-region: ${{ secrets.AWS_REGION }}
+#
+#      - name: Check for existing EC2 instance
+#        id: check_instance
+#        run: |
+#          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=new-key" --query 'Reservations[0].Instances[0].InstanceId' --output text)
+#          if [ "$INSTANCE_ID" = "None" ]; then
+#            echo "::set-output name=instance_exists::false"
+#          else
+#            INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].State.Name' --output text)
+#            if [ "$INSTANCE_STATE" = "terminated" ]; then
+#              echo "::set-output name=instance_exists::false"
+#            else
+#              echo "::set-output name=instance_exists::true"
+#              echo "::set-output name=instance_id::$INSTANCE_ID"
+#            fi
+#          fi
+#
+#      - name: Create EC2 instance (if not exists or terminated)
+#        if: steps.check_instance.outputs.instance_exists == 'false'
+#        id: create_ec2
+#        run: |
+#          VPC_ID=$(aws ec2 describe-vpcs --query 'Vpcs[0].VpcId' --output text)
+#          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups --filters "Name=group-name,Values=cloud-sss" --query "SecurityGroups[0].GroupId" --output text)
+#
+#          if [ "$SECURITY_GROUP_ID" = "None" ]; then
+#            SECURITY_GROUP_ID=$(aws ec2 create-security-group --group-name cloud-sss --description "Security group for cloud instance" --vpc-id $VPC_ID --output text)
+#            aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 22 --cidr 0.0.0.0/0
+#            aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --protocol tcp --port 9090 --cidr 0.0.0.0/0
+#          else
+#            echo "Reusing existing security group: $SECURITY_GROUP_ID"
+#          fi
+#
+#          INSTANCE_ID=$(aws ec2 run-instances --image-id ami-0866a3c8686eaeeba --count 1 --instance-type t2.micro --key-name new-key --security-group-ids $SECURITY_GROUP_ID --user-data file://install-docker.sh --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=new-key},{Key=Environment,Value=development}]' --query 'Instances[0].InstanceId' --output text)
+#
+#          echo "::set-output name=instance_id::$INSTANCE_ID"
+#
+#      - name: Wait for EC2 instance to be running
+#        if: steps.create_ec2.outputs.instance_id != '' || steps.check_instance.outputs.instance_exists == 'true'
+#        run: |
+#          INSTANCE_ID=${{ steps.create_ec2.outputs.instance_id || steps.check_instance.outputs.instance_id }}
+#          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
+#          echo "EC2 instance $INSTANCE_ID is now running."
+#
+#      - name: Create new-key.pem file
+#        run: |
+#          echo "${{ secrets.EC2_KEY }}" > new-key.pem
+#          chmod 600 new-key.pem
+#
+#      - name: Create Docker network on EC2
+#        run: |
+#          INSTANCE_ID=${{ steps.create_ec2.outputs.instance_id || steps.check_instance.outputs.instance_id }}
+#          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
+#          ssh -o StrictHostKeyChecking=no -i new-key.pem ubuntu@$PUBLIC_IP "sudo docker network create my-network || true"
+#
+#      - name: Ensure PostgreSQL container exists
+#        run: |
+#          INSTANCE_ID=${{ steps.create_ec2.outputs.instance_id || steps.check_instance.outputs.instance_id }}
+#          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
+#          if ssh -o StrictHostKeyChecking=no -i new-key.pem ubuntu@$PUBLIC_IP "docker ps -a -q -f name=postgres-container"; then
+#            echo "PostgreSQL container already exists."
+#          else
+#            echo "PostgreSQL container not found. Creating a new one..."
+#            ssh -o StrictHostKeyChecking=no -i new-key.pem ubuntu@$PUBLIC_IP "sudo docker run -d --name postgres-container --network my-network
